version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: work_time_db
    environment:
      POSTGRES_USER: worktime
      POSTGRES_PASSWORD: worktime123
      POSTGRES_DB: worktime_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worktime"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 

  